module.exports = {
  // 'APP_BOUNDARY_ERROR_OCCURED': '内有故障，我们为此深感抱歉。',
  // 'API': 'API',
  // 'AUTO_DETECT_LANGUAGES': '自动语言',
  // 'BASICS': '基本',
  // 'BASIC_USAGE': '基本用法',
  // 'BUILDER': '建造词库',
  // 'COM_OUTPUT_HELLO_WORLD': '输出: 哈咯世界',
  // 'COM_ITS_THAT_SIMPLE': '就这么简单！',
  // 'COPY': '拷贝',
  // 'DICTIONARY': '词典',
  // 'DOC_IN_YOUR_DIRECTORY': '在你的程序的文件夹里, 运行一下的其中一个命令:',
  // 'DOC_UNAVAILABLE': '此文档并不存在',
  // 'DOC_PRIMARY_EXAMPLE_FILE_NAME': 'zh.js',
  // 'DOC_SECONDARY_EXAMPLE_FILE_NAME': 'en.js',
  // 'DOC_PRIMARY_EXAMPLE_HELLO_WORLD': '哈咯世界',
  // 'DOC_SECONDARY_EXAMPLE_HELLO_WORLD': 'Hello world',
  // 'DOC_SETTING_UP_DESC': '首先，你必须先设好一个词库。',
  // 'DOC_SETTING_UP_STRUCT_SUGGESTION': '我们建议您依据以下的例子来配置词库的构造。',
  // 'DOC_USING_NPM': '使用 NPM',
  // 'DOC_USING_YARN': '使用 Yarn',
  // 'DOC_THEN_ADD_SOME_LOC': '随后，把翻译加进每一个语言文件里。',
  // 'DOC_YOU_CAN_ADD_MORE_FILES': '你可以把更多其他语言的文件添加进来',
  // 'DOC_TITLE_INITIALIZING': '初步设定',
  // 'DOC_TITLE_INSTALLATION_SETUP': '安装与配置',
  // 'DOC_NEXT_PARAM': '上一项: %p ▶',
  // 'DOC_PREV_PARAM': '◀ 下一项: %p',
  // 'DOCS': '文档',
  // 'FOOTER_COPYRIGHT': ' © {:year} chin98edwin 版权所有',
  // 'GET_STARTED': '立即开始',
  // 'HERES_HOW_IT_WORKS_NUTSHELL': '主要操作方式如下',
  // 'HOME': '主页',
  // 'INSTALLATION': '安装',
  // 'LOADING_ELLIPSIS': '在载中...',
  // 'LOC_JS_MADE_SIMPLE': 'JavaScript 里的翻译过程从此变得简单',
  // 'SETTING_UP': '配置',
  // 'SWITCH_LANGUAGE': '更换语言',
  // 'SWITCHING_LANGUAGES': '更换语言',
  // 'VIEW_IN_GITHUB': '载 GitHub 阅读',
  // 'LOREM_IPSUM': '滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。是非成败转头空，青山依旧在，惯看秋月春风。一壶浊酒喜相逢，古今多少事，滚滚长江东逝水，浪花淘尽英雄。 几度夕阳红。白发渔樵江渚上，都付笑谈中.......',
  // '': '',
}
