name: CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up...
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn ci:test
